{
    'name': 'Health Insurance',
    'version': '1.0',
    'category': 'Insurance',
    'summary': 'Core Health Insurance Management',
    'author': 'Qasim',
    'depends': ['base','mail', 'account'],
    'data': [
        'security/security.xml',
        'security/record_rules.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/policy_views.xml',
        'views/provider_views.xml',
        'views/claim_views.xml',
        'views/member_views.xml',
        'views/coverage_template_views.xml',
        'views/service_views.xml',
        'views/reinsurance_contract_views.xml',
        'views/reinsurance_bordereau_views.xml',
        'views/reinsurance_bordereau_line_views.xml',
        'views/reinsurance_settlement_views.xml',
        'views/res_company_views.xml',
        'views/menu.xml',
        'data/cron.xml',

    ],
    'installable': True,
    'application': True,
}
